// Login DTO
export interface LoginDto {
  username: string;
  password: string;
}

// Auth Response DTO
export interface AuthResponseDto {
  userId: number;
  username: string;
  email: string;
  fullName: string;
  role: string;
  token: string;
  expiresAt: string;
  requiresEmailVerification?: boolean;
  mustChangePassword?: boolean;
  isFirstLogin?: boolean;
}

// Register Admin DTO
export interface RegisterAdminDto {
  fullName: string;
  email: string;
  username: string;
  password: string;
  confirmPassword: string;
}

// Create Admin DTO (Password auto-generated by backend)
export interface CreateAdminDto {
  fullName: string;
  email: string;
  username: string;
}

// Create Court Authority DTO (Password auto-generated by backend)
export interface CreateCourtAuthorityDto {
  fullName: string;
  email: string;
  username: string;
}

// Create Station Authority DTO (Password auto-generated by backend)
export interface CreateStationAuthorityDto {
  fullName: string;
  email: string;
  username: string;
}

// Change Password DTO
export interface ChangePasswordDto {
  currentPassword?: string;
  newPassword: string;
  confirmPassword: string;
  isForcedChange?: boolean;
}

// User Created Response DTO
export interface UserCreatedResponseDto {
  userId: number;
  username: string;
  email: string;
  fullName: string;
  role: string;
  message: string;
}
