using System.ComponentModel.DataAnnotations;

namespace NoiseSentinel.BLL.DTOs.EmissionReport;

/// <summary>
/// DTO for creating a new emission report from IoT device readings.
/// </summary>
public class CreateEmissionReportDto
{
    [Required(ErrorMessage = "Device ID is required")]
    public int DeviceId { get; set; }

    [Range(0, 10000, ErrorMessage = "CO level must be between 0 and 10,000")]
    public decimal? Co { get; set; }

    [Range(0, 10000, ErrorMessage = "CO2 level must be between 0 and 10,000")]
    public decimal? Co2 { get; set; }

    [Range(0, 10000, ErrorMessage = "HC level must be between 0 and 10,000")]
    public decimal? Hc { get; set; }

    [Range(0, 10000, ErrorMessage = "NOx level must be between 0 and 10,000")]
    public decimal? Nox { get; set; }

    [Required(ErrorMessage = "Sound level is required")]
    [Range(0, 200, ErrorMessage = "Sound level must be between 0 and 200 dBA")]
    public decimal SoundLevelDBa { get; set; }

    [Required(ErrorMessage = "Test date/time is required")]
    public DateTime TestDateTime { get; set; }

    [StringLength(255, ErrorMessage = "ML Classification cannot exceed 255 characters")]
    public string? MlClassification { get; set; }

    // ⚠️ NOTE: Digital signature will be auto-generated by service layer
}