USE fyp_noise_sentinel_db;
GO

-- USER TABLE
CREATE TABLE [USER] (
  [UserID] INT IDENTITY(1,1) PRIMARY KEY,
  [FullName] NVARCHAR(255),
  [Email] NVARCHAR(255) UNIQUE,
  [Username] NVARCHAR(255) UNIQUE,
  [PasswordHash] NVARCHAR(255),
  [IsActive] BIT DEFAULT 1,
  [CreatedAt] DATETIME DEFAULT GETDATE(),
  [RoleID] INT
);
GO

-- ROLE TABLE
CREATE TABLE [ROLE] (
  [RoleID] INT IDENTITY(1,1) PRIMARY KEY,
  [RoleName] NVARCHAR(255) UNIQUE
);
GO

-- POLICE STATION
CREATE TABLE [POLICESTATION] (
  [StationID] INT IDENTITY(1,1) PRIMARY KEY,
  [StationName] NVARCHAR(255),
  [StationCode] NVARCHAR(50),
  [Location] NVARCHAR(255),
  [District] NVARCHAR(255),
  [Province] NVARCHAR(255),
  [Contact] NVARCHAR(50)
);
GO

-- POLICE OFFICER
CREATE TABLE [POLICEOFFICER] (
  [OfficerID] INT IDENTITY(1,1) PRIMARY KEY,
  [UserID] INT,
  [StationID] INT,
  [CNIC] NVARCHAR(20),
  [ContactNo] NVARCHAR(20),
  [BadgeNumber] NVARCHAR(50),
  [Rank] NVARCHAR(100),
  [IsInvestigationOfficer] BIT DEFAULT 0,
  [PostingDate] DATETIME
);
GO

-- JUDGE
CREATE TABLE [JUDGE] (
  [JudgeID] INT IDENTITY(1,1) PRIMARY KEY,
  [UserID] INT,
  [CourtID] INT,
  [CNIC] NVARCHAR(20),
  [ContactNo] NVARCHAR(20),
  [Rank] NVARCHAR(100),
  [ServiceStatus] BIT
);
GO

-- COURT TYPE
CREATE TABLE [COURTTYPE] (
  [CourtTypeID] INT IDENTITY(1,1) PRIMARY KEY,
  [CourtTypeName] NVARCHAR(255)
);
GO

-- COURT
CREATE TABLE [COURT] (
  [CourtID] INT IDENTITY(1,1) PRIMARY KEY,
  [CourtName] NVARCHAR(255),
  [CourtTypeID] INT,
  [Location] NVARCHAR(255),
  [District] NVARCHAR(255),
  [Province] NVARCHAR(255)
);
GO

-- ACCUSED
CREATE TABLE [ACCUSED] (
  [AccusedID] INT IDENTITY(1,1) PRIMARY KEY,
  [FullName] NVARCHAR(255),
  [CNIC] NVARCHAR(20),
  [City] NVARCHAR(100),
  [Province] NVARCHAR(100),
  [Address] NVARCHAR(255),
  [Contact] NVARCHAR(20)
);
GO

-- VEHICLE
CREATE TABLE [VEHICLE] (
  [VehicleID] INT IDENTITY(1,1) PRIMARY KEY,
  [Veh_Reg_Year] DATETIME,
  [PlateNumber] NVARCHAR(50),
  [Make] NVARCHAR(100),
  [Color] NVARCHAR(50),
  [ChasisNo] NVARCHAR(100),
  [EngineNo] NVARCHAR(100),
  [OwnerID] INT
);
GO

-- VIOLATION
CREATE TABLE [VIOLATION] (
  [ViolationID] INT IDENTITY(1,1) PRIMARY KEY,
  [ViolationType] NVARCHAR(255),
  [Description] NVARCHAR(255),
  [PenaltyAmount] DECIMAL(10,2),
  [SectionOfLaw] NVARCHAR(255),
  [IsCognizable] BIT
);
GO

-- IOT DEVICE
CREATE TABLE [IOTDEVICE] (
  [DeviceID] INT IDENTITY(1,1) PRIMARY KEY,
  [DeviceName] NVARCHAR(255),
  [FirmwareVersion] NVARCHAR(100),
  [IsCalibrated] BIT,
  [PairingDateTime] DATETIME,
  [IsRegistered] BIT
);
GO

-- EMISSION REPORT
CREATE TABLE [EMISSIONREPORT] (
  [EmissionReportID] INT IDENTITY(1,1) PRIMARY KEY,
  [DeviceID] INT,
  [CO] DECIMAL(10,2),
  [CO2] DECIMAL(10,2),
  [HC] DECIMAL(10,2),
  [NOx] DECIMAL(10,2),
  [SoundLevel_dBA] DECIMAL(10,2),
  [TestDateTime] DATETIME,
  [Ml_Classification] NVARCHAR(255),
  [DigitalSignatureValue] NVARCHAR(255)
);
GO

-- CHALLAN
CREATE TABLE [CHALLAN] (
  [ChallanID] INT IDENTITY(1,1) PRIMARY KEY,
  [OfficerID] INT,
  [AccusedID] INT,
  [VehicleID] INT,
  [ViolationID] INT,
  [EmissionReportID] INT,
  [EvidencePath] NVARCHAR(255),
  [IssueDateTime] DATETIME,
  [DueDateTime] DATETIME,
  [Status] NVARCHAR(100),
  [BankDetails] NVARCHAR(255),
  [DigitalSignatureValue] NVARCHAR(255)
);
GO

-- FIR
CREATE TABLE [FIR] (
  [FIRID] INT IDENTITY(1,1) PRIMARY KEY,
  [FIRNo] NVARCHAR(50),
  [StationID] INT,
  [ChallanID] INT,
  [DateFiled] DATETIME,
  [FIRDescription] NVARCHAR(500),
  [FIRStatus] NVARCHAR(100),
  [InformantID] INT,
  [InvestigationReport] NVARCHAR(500)
);
GO

-- CASE (renamed with [])
CREATE TABLE [CASE] (
  [CaseID] INT IDENTITY(1,1) PRIMARY KEY,
  [FIRID] INT,
  [JudgeID] INT,
  [CaseNo] NVARCHAR(50),
  [CaseType] NVARCHAR(255),
  [CaseStatus] NVARCHAR(100),
  [HearingDate] DATETIME,
  [Verdict] NVARCHAR(255)
);
GO

-- CASE STATEMENT
CREATE TABLE [CASESTATEMENT] (
  [StatementID] INT IDENTITY(1,1) PRIMARY KEY,
  [CaseID] INT,
  [StatementBy] NVARCHAR(255),
  [StatementText] NVARCHAR(MAX),
  [StatementDate] DATETIME
);
GO

-- =======================
-- FOREIGN KEYS
-- =======================

ALTER TABLE [USER] ADD FOREIGN KEY ([RoleID]) REFERENCES [ROLE] ([RoleID]);
ALTER TABLE [POLICEOFFICER] ADD FOREIGN KEY ([UserID]) REFERENCES [USER] ([UserID]);
ALTER TABLE [POLICEOFFICER] ADD FOREIGN KEY ([StationID]) REFERENCES [POLICESTATION] ([StationID]);
ALTER TABLE [JUDGE] ADD FOREIGN KEY ([UserID]) REFERENCES [USER] ([UserID]);
ALTER TABLE [JUDGE] ADD FOREIGN KEY ([CourtID]) REFERENCES [COURT] ([CourtID]);
ALTER TABLE [CHALLAN] ADD FOREIGN KEY ([OfficerID]) REFERENCES [POLICEOFFICER] ([OfficerID]);
ALTER TABLE [CHALLAN] ADD FOREIGN KEY ([AccusedID]) REFERENCES [ACCUSED] ([AccusedID]);
ALTER TABLE [CHALLAN] ADD FOREIGN KEY ([VehicleID]) REFERENCES [VEHICLE] ([VehicleID]);
ALTER TABLE [CHALLAN] ADD FOREIGN KEY ([ViolationID]) REFERENCES [VIOLATION] ([ViolationID]);
ALTER TABLE [CHALLAN] ADD FOREIGN KEY ([EmissionReportID]) REFERENCES [EMISSIONREPORT] ([EmissionReportID]);
ALTER TABLE [VEHICLE] ADD FOREIGN KEY ([OwnerID]) REFERENCES [ACCUSED] ([AccusedID]);
ALTER TABLE [EMISSIONREPORT] ADD FOREIGN KEY ([DeviceID]) REFERENCES [IOTDEVICE] ([DeviceID]);
ALTER TABLE [FIR] ADD FOREIGN KEY ([StationID]) REFERENCES [POLICESTATION] ([StationID]);
ALTER TABLE [FIR] ADD FOREIGN KEY ([ChallanID]) REFERENCES [CHALLAN] ([ChallanID]);
ALTER TABLE [FIR] ADD FOREIGN KEY ([InformantID]) REFERENCES [POLICEOFFICER] ([OfficerID]);
ALTER TABLE [CASE] ADD FOREIGN KEY ([FIRID]) REFERENCES [FIR] ([FIRID]);
ALTER TABLE [CASE] ADD FOREIGN KEY ([JudgeID]) REFERENCES [JUDGE] ([JudgeID]);
ALTER TABLE [CASESTATEMENT] ADD FOREIGN KEY ([CaseID]) REFERENCES [CASE] ([CaseID]);
ALTER TABLE [COURT] ADD FOREIGN KEY ([CourtTypeID]) REFERENCES [COURTTYPE] ([CourtTypeID]);
GO
